config/routes.rb
Rails.application.routes.draw do
  
  

  root 'pages#home'

  devise_for  :users, 
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations'}
              
  resources :users, only: [:show,:edit]
	resources :gears
  resources :photos


end

app/models/gear.rb
class Gear < ActiveRecord::Base
  belongs_to :user
  has_many :photos

  geocoded_by :location
  after_validation :geocode, if: :location_changed?

  validates :gear_type, presence: true
  validates :price, presence: true
  validates :listing_name, presence: true, length: {maximum: 50}
  validates :location, presence: true
  validates :description, presence: true, length: {maximum: 500}

  

  end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :gear

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, omniauth_providers: [:google_oauth2, :facebook]

   validates :fullname, presence: true, length: {maximum: 40}  
   validates :password,  :format => { :with => /(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/,
   :message => "Password should contain at least 6 characters, one upper case, one lower case and one numeric." }, on: :create
	 validates :password,  :format => { :with => /(?=.*\d)(?=.*[a-z])(?=.*[A-Z])/,
   :message => "Password should contain at least 6 characters, one upper case, one lower case and one numeric." }, on: :update, allow_blank: true
   
    
  validates_date :date_of_birth, :before => lambda { 18.years.ago },
                         :before_message => "must be at least 18 years old", if: :validate_date_of_birth?

    def validate_date_of_birth?
     return false if provider == 'google_oauth2' || provider == 'facebook'
      true
    end

   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

   has_many :gears

   def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.fullname = auth.info.name
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0,20]
        user.skip_confirmation! unless user.confirmed?
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_paramters, if: :devise_controller?

  protected
  	def configure_permitted_paramters
  		devise_parameter_sanitizer.for(:sign_up) << :fullname << :date_of_birth
  		devise_parameter_sanitizer.for(:account_update) << :fullname << :description << :email << :password << :live_in << :gender << :current_password << :date_of_birth << :avatar
  	end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :set_gear, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @gears= current_user.gears
  end

  def show
    @photos = @gear.photos
  end

  def new
    @gear = current_user.gears.build
  end

  def create
     @gear = current_user.gears.build(gear_params)

     if @gear.save
      
      if params[:images]
        params[:images].each do |image|
          @gear.photos.create(image: image)
        end
      end
      @photos = @gear.photos
      redirect_to edit_gear_path(@gear), notice: "Saved..."
    else
      render :new
    end
  end

  def edit
    if current_user.id == @gear.user.id
    @photos = @gear.photos
  else
    redirect_to root_path, notice: "You don't have permission."
  end
 end

  def update
    if @gear.update(gear_params)

      if params[:images]
        params[:images].each do |image|
          @gear.photos.create(image: image)
        end
      end
    
      redirect_to edit_gear_path(@gear), notice: "Updated..."
      
    else
      render :edit
    end

  end

  private
  def set_gear
      @gear = Gear.find(params[:id])
  end

  def gear_params
      params.require(:gear).permit(:gear_type, :price, :listing_name, :location, :description, :is_insurance, :active)
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	
	def google_oauth2
	    @user = User.from_omniauth(request.env['omniauth.auth'])

	    if @user.persisted?
	      sign_in_and_redirect @user, :event => :authentication
	      set_flash_message(:notice, :success, :kind => "Google") if is_navigational_format?
	    else
	    	session["devise.google_oauth2_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
	    end
	  end

	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])	

		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication
			set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def 
	@photo = Photo.find(params[:id])
	gear = @photo.gear	
	
	@photo.destroy
	@photos= Photo.where(gear_id: gear.id)

	respond_to :js
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	protected
		def update_resource(resource, params)
			resource.update_without_password(params)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def edit
	  @user = User.find(params[:id])
	end

	def update
		 @user = User.find(params[:id])
	  if @user.update(user_params)
	  	UserMailer.changepass_email(@user).deliver_now
	    redirect_to new_user_session_path, notice: 'Password was successfully updated.'
	  else
	    redirect_to edit_user_path(current_user.id), alert: 'Password should contain at least 6 characters, one upper case, one lower case and one numeric'
	  end
	end

	private
	  def user_params
	    params.require(:user).permit(:password, :password_confirmation)
	  end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		if user.image
			user.image
		else
			"/images/missing.png"
		end
	end
end

app/helpers/gears_helper.rb
module GearsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/gears/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
	Create your gear item	
	</div>
	<div class="panel-body">
	   <div class="container">
	
		<%= form_for @gear, :html => {multipart: true} do |f| %>
		
		<div class="row">
			<div class="col-md-4 select">
				<div class="form-group">
					<label> Gear Category:</label>
					<%= f.select :gear_type, [["Bike","Bike"],["Surfing board","Surfing board"], ["Snow board","Snow board"],["Motorbikes","Motorbikes"],["Tent","Tent"]], id: "gear_type", prompt: "Select...", class: "form-control" %>
				</div>
			</div>

		</div>

		
		<div class="row">
		<div class="form-group">
			<label> Gear specification: name or type of gear</label>
			<%= f.text_field :listing_name, placeholder: "Be clear and descriptive", class: "form-control" %>
		</div>
	
		</div>
		
		<div class="row">
        	<div class="form-group">
        		<label>Description:</label>
        		<%= f.text_area :description, row: 5, placeholder: "Tell about your gear", class: "form-control" %>
        	</div>
        </div>
		
        <div class="row">
        	<div class="form-group">
        		<label>Address Location:</label>
        		<%= f.text_area :location, placeholder: "What is your address", class: "form-control" %>
        	</div>
		</div>


		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
					<label>Daily Price:</label>
					<div class="input-group">
						<div class="input-group-addon">$</div>
						<%= f.text_field :price, placeholder: "eg. $100", class: "form-control" %>
					</div>
				</div>
			</div>
		</div>
 

		<div class="row">			
				<div class="form-group">
					<%= f.check_box  :is_insurance %> Do you want insurance on your gear item
				</div>
		</div>


		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
					<span class= "btn btn-default btn-file">
						<i class= "fa fa-cloud-upload fa-lg"></i> Upload Photos
						<%= file_field_tag "images[]", type: :file, multiple: true %>
					</span>
				</div>
			</div>
		</div>	

		<div id= "photos"><%= render 'photos/list' %></div>

		

		<div class="row">
			<div class="form-group">
				<%= f.check_box :active %> Do you agree to the terms and conditions
			</div>
		</div>

		<div class="actions">
			<%= f.submit "Save", class: "btn btn=primary"%>
		</div>


		<% end %>
	</div>
		
	</div>

</div>

app/views/gears/create.html.erb
<h1>Gears#create</h1>
<p>Find me in app/views/gears/create.html.erb</p>

app/views/gears/edit.html.erb
<%= render 'form' %>

app/views/gears/index.html.erb
<div class="row">
	<div class="col-md-3">
	<ul class = "sidebar-list">
		<li class="sidebar-item"><%= link_to "Your listing", gears_path, class: "sidebar-link active" %></li>
		
		<li class="sidebar-item"><%= link_to "Your Reservation", gears_path, class: "sidebar-link" %></li>

	</ul>	
	</div>
<div class="col-md-9">
<div class="panel panel-default">
	<div class="panel-heading">
		Listings
	</div>
	<div class="panel-body">
		<% @gears.each do |gear| %>
		<div class="row">
			
			<div class="col-md-3 right">
				<h5><%= gear.gear_type %></h5>
			</div>

			<div class="col-md-3 right">
				<h5><%= gear.listing_name %></h5>
			</div>

			<div class="col-md-3 right">
				<h5><%= gear.price %></h5>
			</div>

			<div class="col-md-3 right">
				<%= link_to "Update", edit_gear_path(gear), class: "btn btn-primary" %>
			</div>
		</div>
		<% end %>
	</div>

</div>
	
</div>

</div>

app/views/gears/new.html.erb
<%= render 'form' %>

app/views/gears/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		
	<!-- Image -->
	<div class="row">
				<div class="col-md-12">
					<%= image_tag @photos[0].image.url(), class: "img-responsive" if @photos.length > 0 %>
				</div>
	</div>
	<br>
	
	<!-- Main Info-->
	<div class="row">
				<div class="col-md-8">
					<div class="row">
						<div class="col-md-3 text-center">
							 <%= image_tag avatar_url(@gear.user), class: "img-circle avatar-small" %><br><br>
						     <%= @gear.user.fullname %>
						</div>

						<div class="col-md-9">
							<h4><%= @gear.listing_name %> </h4>
							<%= @gear.location %>
						
							<div class="row text-center row-space-1">
								<div class="col-sm-3">
									<i class="fa fa-cog fa-spin fa-3x fa-fw"></i>
									<span class="sr-only">Loading...</span>
								</div>
							</div>
								
							<div class="row text-center">
								<div class="col-sm-3">
									<%= @gear.gear_type %>
								</div>
							</div>

						</div>
					</div>
			  </div>	
		      <div class="col-md-4">
	          <!--Reservation Form -->
	          </div>
	</div>

    <!-- About -->
    <div class- "row">
        <div class="col-md-12">
        	<h2> About this listing </h2>
        	<p> <%= @gear.description %></p>
        </div>    	
    </div>

    <!-- Amenities-->
    <div class="row">
    	<div class="col-md-2">
    		<p>Insurance</p>
    	</div>
    	<div class="col-md-10">
    		<div class="row">
    			<div class="col-md-6">
    				<ul class="insurance">
    					<li class= "<%='text-line-through' if !@gear.is_insurance %>">Is your gear item insured</li> 
    				</ul>
    			</div>
    		</div>
    	</div>
    </div>
		
		<!-- Carousel -->
	<div class="row">
		<div class="col-md-10 col-md-offset-1">					
			<div id="myCarousel" class="carousel slide" data-ride="carousel">

			  <% if @photos %>
			   <!-- Indicators -->
			  <ol class="carousel-indicators">
					  <% @photos.each do |photo| %>
					    <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
			    	 <% end%>
			  		</ol>
			  <% end %>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" role="listbox">
			    <% if @photos %>
			   		 <% @photos.each do |photo| %>
			    		<div class="item <%= 'active' if photo.id == @photos[0].id %>">
			      	<%= image_tag photo.image.url() %>
			    </div>
			    	<% end %>
			    <% end %>
			  </div>

			  <!-- Left and right controls -->
			  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>


		</div>
	</div>

	<br>
	<hr>

	<!-- Google Map -->

	<div class="row">
		<div class="col-md-12"> 

			<div id="map"></div>
				<style>
	     		 #map {
	       			 width: 100%;
	      		     height: 400px;
	      				}
	   			 </style>

	   			 <script src= "https://maps.googleapis.com/maps/api/js"> </script>
	   			 <script>
	   			 	function initialize() {
	   			 		var mapCanvas = document.getElementById('map');
	   			 		var mapOptions = {
	   			 			center: new google.maps.LatLng(<%= @gear.latitude %>, <%= @gear.longitude %>),
	   			 			zoom: 14,
	   			 			mapTypeId: google.maps.MapTypeId.ROADMAP
	   			 		}
	   			 		var map = new google.maps.Map(mapCanvas, mapOptions);
	   			 		
	   			 		var marker = new google.maps.Marker ({
	   			 			position: new google.maps.latLng (<%= @gear.latitude %>, <%= @gear.longitude %>),title: "Gohub"
	   			 		});
	   			 		marker.setMap(map);
	   			 	}
	   			 	google.maps.event.addDomListener(window, 'load', initialize);
	   			 </script>


			</div>
	</div>
		



</div>
</div>

app/views/gears/update.html.erb
<h1>Gears#update</h1>
<p>Find me in app/views/gears/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GO HUB</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'shared/navbar' %>

    <%= render 'shared/message' %>

    <div class="container">
      <%= yield %>  
    </div>
    
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the world of GO-HUB</h1>
<p><i>Meeting    Sharing    Caring  </i> </p>

app/views/photos/_list.html.erb
<% if @photos %>

	<div class= "row">
		<% @photos.each do |photo| %>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading preview">
						<%= image_tag photo.image.url() %>
					</div>
					<div class="panel-body">
						<span class = "pull-right">
							<%= link_to photo, remote: true, method: :delete, data: {confirm: "Are you sure"}  do %>

									<i class= "fa fa-times fa-lg"></i>

							<% end %>
						</span>
					</div>
				</div>
			</div>
		<% end %>
	</div>

<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><i>GO HUB</i></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Events</a></li>

        <% if(!user_signed_in?) %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
         <li>
          <a href="#"><i class="fa fa-home fa-lg"></i> Become a Host</a>
          
        </li>

        <li>
        <a href="#"><i class="fa fa-envelope" aria-hidden="true"></i>Messages</a>
        </li>
    
        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.fullname %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Creat Gear", new_gear_path %></li>
              <li><%= link_to "My Gearlist", gears_path %></li>
              <li><%= link_to "View My Profile", user_path(current_user.id)%></li>
              <li><%= link_to "Edit My Profile", edit_user_registration_path %></li>
              <li><%= link_to "Change Password", edit_user_path(current_user.id)%></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
         <li> <%= image_tag avatar_url(current_user), class: "round-image-50" %>&nbsp;
        </li>
        <% end %>

      

       <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Help<span class="caret"></span></a>
          <ul class="dropdown-menu">
                <li><a href="#">How does it work</a></li>
                <li><a href="#">Cookies</a></li>
                <li><a href="#">Terms and Conditions</a></li>
                <li><a href="#">Contact us</a></li>
                <li><a href="#">FAQ</a></li>
              </ul>
      </ul>
      </li>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 text-center">
      
      <div class="panel panel-default">
      <div class="panel-heading"><h2>Change Password</h2></div>  
      <div class="panel-body"> 


<%= form_for(@user) do |f| %>
 <div class="row">
   <label class="col-xs-4" for="password">New Password</label>
   <div class="col-xs-8">
   <%= f.password_field :password, autocomplete: "off", :placeholder => "6 characters, one uppercase, one lowercase and one numeric", :class => 'form-control' %>
   </div>
 </div></br></br>
 <div class="row">
   <label class="col-xs-4" for="password">Confirm Password</label>
   <div class="col-xs-8">
   <%= f.password_field :password_confirmation, autocomplete: "off", :placeholder => "Repeat password ", :class => 'form-control' %>
   </div>
 </div></br></br>

  <div class="actions">
    <%= f.submit "Save", :class => "btn btn-primary" %>
  </div>
<% end %>
</div></div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-3">
		
		<div class="panel panel-default">
			<div class="panel-heading">My Profile</div>	
			<div class="panel-body">
				<%= image_tag(current_user.avatar.url(:medium)) %>
				<h2><%= @user.fullname %></h2>
				<%= @user.email%><br>
				<%= @user.phone_number%><br>
				<%= @user.live_in%><br>
				<div class="describe row-space-3">
				<%= @user.description %>
				</div>
			</div>
		</div>
	</div>